### ISSUE TITLE
Twitch hide bar no longer working

### ISSUE THREAD

**Issue by thorrentking** [ky-is/twitch-vod-unspoiler#1]
Hi,
It was working about a few days ago, then it just suddenly stops working. I'm not sure if it is because of chrome update, or twitch update.

I tried to roll back my chrome version, but it didn't help. @ky-is if you can assist, that'll be great.

**Comment by jordanking** [comment]
This is fixed for me, might be a twitch-side change.

**Comment by ky-is** [comment]
Twitch updated their styling again shortly after the last update which broke things again. I described this problem in https://github.com/ky-is/twitch-vod-unspoiler/commit/8d0d3ab3fee7685a2db186f7c58ccbb3cfb723f8.

Please let me know if you're still seeing any issues in 2.2 (pending review from the Chrome Store). Thanks for your patience.

**Comment by thorrentking** [comment]
Yeah for 2.1 it worked for a little while, then could not forward/rewind videos anymore. As of now, 2.2 is working as intended. Many thanks @ky-is ! Really appreciate the effort.
